---
# Source: wordpress-stack/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpapp
  id: 
  env: 
  labels:
    app: wp
    env: dev
    id: C0910891
    stack: wordpress
spec:
  selector:
    matchLabels:
      app: wp
      env: dev
      id: C0910891
      stack: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wp
        env: dev
        id: C0910891
        stack: wordpress
    spec:
      containers:
      - name: wpapp
        image: wordpress:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
